### ISSUE TITLE
What's your favorite project on GitHub and why?

### ISSUE THREAD

**Issue by sindresorhus** [cheeaun/ama#11]

**Comment by cheeaun** [comment]
I've always been impressed by these two projects:
- [mbostock/queue](https://github.com/mbostock/queue) - It's amazing how little code it takes to do so much, being just a _simple_ async helper library. The feature that I always use (and wish other libraries have) is the `parallelism` parameter for the `queue([parallelism])` method, really useful when for example, I need to perform a lot of AJAX calls but batch them together, 3 at a time.
- [lodash](https://github.com/lodash/lodash) - This project has great documentation, complete with performance benchmarks, full code coverage, testing, compatibility support, and very customizable modular builds. From time to time when I code, I always refer to `lodash`'s source code and see how it's done.
