### ISSUE TITLE
What are your favorite apps on OS X and iOS?

### ISSUE THREAD

**Issue by chuyeow** [cheeaun/ama#6]
You know, stuff that you find indispensable, use very often, or are delightful.

**Comment by cheeaun** [comment]
I'll just list the not-so-common ones, as of 9th July 2015:

**iOS**:
- [Citymapper](https://itunes.apple.com/sg/app/citymapper-ultimate-real-time/id469463298?mt=8) - initially not so useful, but now, it has improved dramatically, though it's very city-specific. Good for travelling and sometimes useful for travelling in Singapore too.
- [Accuweather](https://itunes.apple.com/sg/app/accuweather-weather-for-life/id300048137?mt=8) - the Real Feel feature is pretty accurate. That's all I use from this app.
- [Weblock](https://itunes.apple.com/sg/app/weblock-adblock-for-apps-websites/id558818638?mt=8) - block ads :grin: 
- [NoteDash](https://itunes.apple.com/us/app/notedash/id936390414?mt=8) - useful when I need quick info from the notification center on iOS. When travelling, I put my hotel address.
- [Klok](https://itunes.apple.com/us/app/klok-time-elegantly/id470798418?mt=8) - for tracking time in other time zones. Also good for travelling or when collaborating with people in other time zones.
- [CodeHub](https://itunes.apple.com/sg/app/codehub-github-for-ios/id707173885?mt=8) - GitHub stuff
- [TripIt](https://itunes.apple.com/sg/app/tripit-travel-organizer-free/id311035142?mt=8) - for keeping track of travel itineraries
- [9GAG](https://itunes.apple.com/sg/app/9gag-funny-lol-meme-gif/id545551605?mt=8) - for the lolz

**Mac**:
- [MiniUsage](https://itunes.apple.com/us/app/miniusage/id416285394?mt=12) - I only need to show the download speed rate
- [Clean](https://itunes.apple.com/us/app/clean/id418412301?mt=12) - automagically clean my desktop every day
- [Window Tidy](https://itunes.apple.com/us/app/window-tidy/id456609775?mt=12) - drag-n-drop-style window management (not keyboard shortcuts)

**Comment by chuyeow** [comment]
Awesome, I'll check those out, especially Citymapper and Clean (I already use some of the rest or an equivalent.
