### ISSUE TITLE
How do you get your next idea to work on?

### ISSUE THREAD

**Issue by sayanee** [cheeaun/ama#7]
You have created so many useful projects for the public ([busrouter](https://github.com/cheeaun/busrouter-sg)) as well as the tech industry ([hackerweb](https://github.com/cheeaun/hackerweb)). 

How do you get these ideas? Also, how do you balance between **maintaining** current open source projects vs. **creating** new projects?

**Comment by cheeaun** [comment]
From my point of view, there are many "types" of projects. It can be a full-fledged framework, a library you build on top of another framework, an app you build for others, etc. I've tried a bunch of them and finally decided that the best type is to build apps for _myself_.

I always say that it's **easy** to create things, but **very difficult** to maintain them. If you just focus on the creation part and not the maintenance part, that's just 50% (or less?) of the whole "app-building" experience. And what I mean by the **whole** experience also includes other aspects like _actually_ launching the project/product to the public, the marketing work to make people know your project, and customer support for people having issues with your project.

So, going back to the point which I mention building apps for _myself_. I realise that I feel more likely to maintain the project if I'm using it myself. But that doesn't mean I'm being selfish and only build whatever I want. Basically I build apps for myself with the public in mind. This is when open-sourcing things and launching apps to the public, helps. There are some apps I built which I don't think _anyone_ would use at all, and one day, I realise there are over 1K users using my app every day.

I usually don't find for ideas. For me, ideas come from being aware of things around you. Let me give an example:

During ReddotRubyConf this year, I was sitting on the middle row of the seats and realise that the lights are very bright. It makes it hard to focus on the speaker and creates stress for the eyes. At that moment, somehow it reminds me when I was attending Beyond Tellerrand conference. I realise that whenever the talk session begins and the speaker starts talking, someone (or something?) dims out the light in the seats area. It's not a sudden dim, but a smooth transitional light dim so most people won't even notice it. When the talk is done, the light slowly brighten up.

Obviously the example above is not a "project", but pretty much applicable. First is being aware of things around you, be curious about them, think about them, and things just naturally flow from that point.

**Comment by sayanee** [comment]
Thanks @cheeaun for an in-depth explanation. This echoes many of my thoughts too 🌟

**Comment by valentine** [comment]
:heart: your reply, @cheeaun! :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by winston** [comment]
> During ReddotRubyConf this year, I was sitting on the middle row of the seats and realise that the lights are very bright. It makes it hard to focus on the speaker and creates stress for the eyes.

Why never tell me? :sob:

**Comment by cheeaun** [comment]
@winston now you know :stuck_out_tongue:

**Comment by JuanitoFatas** [comment]
:+1:

**Comment by redhae** [comment]
:+1:

**Comment by ryantss** [comment]
:+1:
