### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [cheeaun/ama#9]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by cheeaun** [comment]
![2015-07-11 19 16 02](https://cloud.githubusercontent.com/assets/2296/8633580/c88bc7ce-2801-11e5-8a2f-302b4d605e89.png)

Running iOS9 public beta.
